# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from tkinter import filedialog
from selenium import webdriver
from tkinter import *
import xlwings as xw
import time


class Ui_back(object):
    def __init__(self, navegador, sheet):
        self.navegador = navegador
        self.sheet = sheet

    def main(self):
        navegador = self.navegador
        sheet = self.sheet
        wb = xw.Book(sheet)
        sht1 = wb.sheets['Plan1']
        sht1.range('A1').value = 'NOME'
        sht1.range('B1').value = 'ENDEREÇO'
        sht1.range('C1').value = 'NUMERO'

        if(navegador == '1'):
            driver = webdriver.Chrome()
        if(navegador == '2'):
            driver = webdriver.Firefox()

        driver.get('https://www.google.com.br/maps/')
        time.sleep(5)
        k = 2

        nome_ant = numero_ant = endereco_ant = ''
        while True:
            try:
                nome = driver.find_element_by_xpath(
                    '//*[@id="pane"]/div/div[1]/div/div/div[2]/div[1]/div[1]/div[1]/h1/span[1]')
                numero = driver.find_element_by_css_selector(
                    "[data-tooltip='Copiar número de telefone']")
                endereco = driver.find_element_by_css_selector(
                    "[data-item-id='address']")
                if(len(nome.text) > 0 and len(numero.text) > 0 and len(endereco.text) > 0):
                    if(nome_ant != nome.text and numero_ant != numero.text and endereco_ant != endereco.text):
                        print(nome.text)
                        print(numero.text)
                        print(endereco.text)
                        print('')
                        sht1.range('A'+str(k)).value = nome.text
                        sht1.range('B'+str(k)).value = numero.text
                        sht1.range('C'+str(k)).value = endereco.text
                        nome_ant = nome.text
                        numero_ant = numero.text
                        endereco_ant = endereco.text
                        k = k+1
            except:
                pass


class Ui_MainWindow(object):
    def verificacao(self):
        try:
            self.verificacao_var()
            MainWindow.hide()
            Ui_back.main(self.passing)
        except Exception as e:
            print("ERRO NA VERIFICACAO (def verificacao)")
            print(e)

    def verificacao_var(self):
        try:
            if(self.radioButton.isChecked()):
                self.navegador = '1'
            if(self.radioButton_2.isChecked()):
                self.navegador = '2'
            self.passing = Ui_back(self.navegador, self.sheet)
        except Exception as e:
            print("ERRO NA VERIFICAÇÃO DE VARIÁVEIS (def verificacao_var)")
            print(e)

    def showChrome(self):
        try:
            self.toolButton_4.setIcon(self.icon2)
            self.toolButton_4.show()
        except Exception as e:
            print("ERRO AO EXIBIR ÍCONE DO CHROME (def showChrome)")
            print(e)

    def showFirefox(self):
        try:
            self.toolButton_4.setIcon(self.icon1)
            self.toolButton_4.show()
        except Exception as e:
            print("ERRO AO EXIBIR ÍCONE DO FIREFOX (def showFirefox)")
            print(e)

    def escolherPlanilha(self):
        try:
            root = Tk()
            root.withdraw()
            self.sheet = filedialog.askopenfilename(
                title='Escolher planilha para registro de dados')
            self.nomelista = self.sheet.split('/')
            self.nomelista = self.nomelista[-1]
            self.label_4.setText(self.nomelista)
            self.label_4.show()
        except Exception as e:
            print("ERRO AO ESCOLHER PLANILHA (def escolherPlanilha)")
            print(e)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(352, 450)
        MainWindow.setStyleSheet(open('interface.css').read())
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 110, 331, 111))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 5, 251, 31))
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(70, 50, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(70, 70, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.toolButton_4 = QtWidgets.QToolButton(self.frame)
        self.toolButton_4.setGeometry(QtCore.QRect(160, 50, 101, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/firefox.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon)
        self.toolButton_4.setIconSize(QtCore.QSize(200, 200))
        self.toolButton_4.setObjectName("toolButton_4")
        self.icon1 = QtGui.QIcon()
        self.icon1.addPixmap(QtGui.QPixmap("img/firefox.png"),
                             QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon2 = QtGui.QIcon()
        self.icon2.addPixmap(QtGui.QPixmap("img/chrome.png"),
                             QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.hide()
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 331, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(60, 50, 251, 31))
        self.label.setObjectName("label")
        self.toolButton_5 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_5.setGeometry(QtCore.QRect(0, 10, 71, 71))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/maps.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon1)
        self.toolButton_5.setIconSize(QtCore.QSize(200, 200))
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_5.raise_()
        self.label.raise_()
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(10, 350, 331, 91))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 12, 311, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_23 = QtWidgets.QLabel(self.frame_4)
        self.label_23.setGeometry(QtCore.QRect(20, 70, 291, 16))
        self.label_23.setObjectName("label_23")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 230, 331, 111))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 40, 161, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.escolherPlanilha)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(80, 10, 191, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 311, 20))
        self.label_4.setObjectName("label_4")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.hide()
        MainWindow.setCentralWidget(self.centralwidget)

        self.radioButton.toggled.connect(self.showChrome)
        self.radioButton_2.toggled.connect(self.showFirefox)
        self.pushButton_7.clicked.connect(self.verificacao)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Google Maps Crawler"))
        self.label_2.setText(_translate("MainWindow", "SELECIONAR NAVEGADOR:"))
        self.radioButton.setText(_translate("MainWindow", "Chrome"))
        self.radioButton_2.setText(_translate("MainWindow", "Firefox"))
        self.toolButton_4.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "GOOGLE MAPS CRAWLER"))
        self.toolButton_5.setText(_translate("MainWindow", "..."))
        self.pushButton_7.setText(_translate(
            "MainWindow", "ABRIR GOOGLE MAPS"))
        self.label_23.setText(_translate(
            "MainWindow", "Versão 1.0.0 | Made by Lucas Alves, 2021 | Github: @lucasfdelis"))
        self.pushButton_5.setText(_translate("MainWindow", "SELECIONAR"))
        self.label_3.setText(_translate("MainWindow", "SELECIONAR PLANILHA:"))
        self.label_4.setText(_translate(
            "MainWindow", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
